name: CI Pipeline

# Define when the workflow should be triggered
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: git clone https://github.com/NaniReddy9533/github-actions.git ./
        # Replace "NaniReddy9533/your-repo-name" with the appropriate GitHub repository URL

      - name: Build
        run: |
          echo "Building the project..."
     
      - name: Test
        run: |
          echo "Running tests..."
